### ISSUE TITLE
official pmacct Docker containers

### ISSUE THREAD

**Issue by paololucente** [kvitex/pmacct-docker-kafka#1]
Dear Victor ( @kvitex ),

As you may know, there are official containers for pmacct available on DockerHub, ie. https://hub.docker.com/r/pmacct/sfacctd , https://hub.docker.com/r/pmacct/nfacctd (or searching the keyword 'pmacct' on DockerHub). As we did venture in offering containers for only a little time and we are still learning, i was curious whether you had to create your own container for some use-case that you could not solve with the official ones. If you got one moment for a reply, any feedback is highly appreciated.

Thanks,
Paolo

**Comment by kvitex** [comment]
> Dear Victor ( @kvitex ),
> 
> As you may know, there are official containers for pmacct available on DockerHub, ie. https://hub.docker.com/r/pmacct/sfacctd , https://hub.docker.com/r/pmacct/nfacctd (or searching the keyword 'pmacct' on DockerHub). As we did venture in offering containers for only a little time and we are still learning, i was curious whether you had to create your own container for some use-case that you could not solve with the official ones. If you got one moment for a reply, any feedback is highly appreciated.
> 
> Thanks,
> Paolo

Hello, Paolo.

I have started to use my own image before the official ones appeared, and much earlier then this project on github was started.
Now I have tested official image and tried it in production environment.
Everything looks fine and I think I will use the officials  further.
Any issues will be reported at pmacct project.

Thank you match for your message.

**Comment by paololucente** [comment]
Wonderful, thanks Victor for your feedback, much appreciated!
